plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.5-beta'
}

version = '1.0.0'
group = 'com.yourname.activeragdoll'

repositories {
    mavenCentral()
    flatDir {
        dirs 'libs'
    }
}

base {
    archivesName = 'activeragdoll'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

neoForge {
    version = '21.1.84'

    runs {
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        activeragdoll {
            sourceSet(sourceSets.main)
        }
    }
}

dependencies {
    implementation name: 'ragdoll_reactions-1.21.1-0.7.0'
}