modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="activeragdoll"
version="1.0.0"
displayName="Active Ragdoll Addon"
authors="galadmitro"
description="Active ragdoll physics toggle addon."

[[dependencies.activeragdoll]]
    modId="neoforge"
    type="required"
    versionRange='[21.1.0,)'

[[dependencies.activeragdoll]]
    modId="minecraft"
    type="required"
    versionRange='[1.21.1,)'

[[dependencies.activeragdoll]]
    modId="ragdoll_reactions"
    type="required"
    versionRange='[0.7.0,)'
    ordering="AFTER"